import 'package:new_maps/core/utils/constant/app_image_asset.dart';
import 'package:new_maps/data/models/medicine.dart';

List<Medicine> medicinesData = [
  Medicine(
      id: 1,
      nameEn: 'bandol',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 2,
      nameEn: 'Aomal',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m1,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 3,
      nameEn: 'Hub',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m2,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 4,
      nameEn: 'nameEn',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m3,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 5,
      nameEn: 'normal',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m4,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 6,
      nameEn: 'nameEn',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m5,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 7,
      nameEn: 'head medicine',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 8,
      nameEn: 'stmace',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m1,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 9,
      nameEn: 'nameEn',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m2,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 1,
      nameEn: 'bueaty medicine',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m3,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 1,
      nameEn: 'nameEn',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m4,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
  Medicine(
      id: 1,
      nameEn: 'nameEn',
      nameAr: 'أسم عربي',
      imageUrl: AppImageAsset.m5,
      description: 'this is a new nice medicine for you ',
      price: 1000,
      count: 1,
      subCategoryId: 2,
      pharmacyId: 4, status: 'active'),
];
