import 'package:new_maps/core/utils/constant/app_image_asset.dart';
import 'package:new_maps/data/models/pharmacy.dart';

List<Doctor> phparmaciesData = [
  Doctor(
      id: 1,
      name: 'صيدلية اليمن السعيد',
      password: 'password',
      image: AppImageAsset.pharmacy,
      address: 'صنعاء ',
      numberOfViewDays: 12,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 2,
      name: 'أبن حيان',
      password: 'password',
      image: 'image',
      address: 'صنعاء شارع تعز',
      numberOfViewDays: 30,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 3,
      name: 'الحياة',
      password: 'password',
      image: 'image',
      address: 'صنعاء حزيز',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 4,
      name: 'صيدلية الشروق',
      password: 'password',
      image: 'image',
      address: 'صنعاء جولة تعز',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 5,
      name: 'صيدلية الأمل',
      password: 'password',
      image: 'image',
      address: 'صنعاء الصافية',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 5,
      name: 'صيدلية النور',
      password: 'password',
      image: 'image',
      address: 'صنعاء شارع الستين',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 5,
      name: 'صيدلية أبن جابر',
      password: 'password',
      image: 'image',
      address: 'صنعاء حوار مستشفى النور',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 5,
      name: 'صيدلية السبعين',
      password: 'password',
      image: 'image',
      address: 'صنعاء مديرة السبعين',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
  Doctor(
      id: 5,
      name: 'صيدلية الثقة',
      password: 'password',
      image: 'image',
      address: 'صنعاء التحرير',
      numberOfViewDays: 20,
      phoneNumber: '',
      status: ''),
];
