// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC0z72y9pMAKfl6MggtS_Vq02aLB1Bn0p4',
    appId: '1:1039474090033:web:23822dfe32a53ceb8ff510',
    messagingSenderId: '1039474090033',
    projectId: 'maps-b68fe',
    authDomain: 'maps-b68fe.firebaseapp.com',
    storageBucket: 'maps-b68fe.appspot.com',
    measurementId: 'G-11258S8Q04',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBuyz3sgW4iV2TPi76R0iXhFHtuXhzdOg',
    appId: '1:1039474090033:android:fc05f3ae123f46c28ff510',
    messagingSenderId: '1039474090033',
    projectId: 'maps-b68fe',
    storageBucket: 'maps-b68fe.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAiIrru8Bu0sG-SUDyibLnYmwCxaaCmmOY',
    appId: '1:1039474090033:ios:cad5137a087a5fc58ff510',
    messagingSenderId: '1039474090033',
    projectId: 'maps-b68fe',
    storageBucket: 'maps-b68fe.appspot.com',
    iosBundleId: 'com.example.newMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAiIrru8Bu0sG-SUDyibLnYmwCxaaCmmOY',
    appId: '1:1039474090033:ios:bea5d0a1a1eda4d18ff510',
    messagingSenderId: '1039474090033',
    projectId: 'maps-b68fe',
    storageBucket: 'maps-b68fe.appspot.com',
    iosBundleId: 'com.example.newMaps.RunnerTests',
  );
}
