// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsgMmkNFbugbkFsLIuCAcQ8BG62qScSsc',
    appId: '1:900551315657:web:e120c5967d68af7f6fbd18',
    messagingSenderId: '900551315657',
    projectId: 'maps-27bc3',
    authDomain: 'maps-27bc3.firebaseapp.com',
    databaseURL: 'https://maps-27bc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maps-27bc3.appspot.com',
    measurementId: 'G-N756BL3S9H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6HLaJiCGYaaRDTNbP6VMpaIp8GldggNw',
    appId: '1:900551315657:android:00107a42a302d5596fbd18',
    messagingSenderId: '900551315657',
    projectId: 'maps-27bc3',
    databaseURL: 'https://maps-27bc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maps-27bc3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAaUBgzpUtr5j7SJySUtuYZzX0bSSPzDlQ',
    appId: '1:900551315657:ios:71ebde71c7cde5c76fbd18',
    messagingSenderId: '900551315657',
    projectId: 'maps-27bc3',
    databaseURL: 'https://maps-27bc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maps-27bc3.appspot.com',
    iosBundleId: 'com.example.maps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAaUBgzpUtr5j7SJySUtuYZzX0bSSPzDlQ',
    appId: '1:900551315657:ios:462a1e19ce1822366fbd18',
    messagingSenderId: '900551315657',
    projectId: 'maps-27bc3',
    databaseURL: 'https://maps-27bc3-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'maps-27bc3.appspot.com',
    iosBundleId: 'com.example.maps.RunnerTests',
  );
}
